# This is a basic workflow to help you get started with Actions

name: Deploy Lambda API

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    env:
      DOTNET_NOLOGO: true  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get source from GitHub
        uses: actions/checkout@v2
        
      - name: Prepare .NET version
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      
      - name: Build and Publish  
        run: dotnet publish -c Release -o release /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false
      
      - name: Deploy Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: blazure-api
          zip_file: src/release/Blazure.Api.zip
          memory_size: 128
          timeout: 1
          handler: Blazure.Api::Blazure.Api.LambdaEntryPoint::FunctionHandlerAsync
          role: ${{ secrets.AWS_LAMBDA_ROLE }}
          runtime: dotnetcore3.1
