# This is a basic workflow to help you get started with Actions

name: Deploy Lambda API

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    env:
      DOTNET_NOLOGO: true  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get source from GitHub
        uses: actions/checkout@v2
        
      - name: Prepare .NET version
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
        
      - name: Install AWS Global Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
      
      - name: Build and Publish  
        run: dotnet lambda deploy-function --aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --aws-secret-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ${{ secrets.AWS_REGION }} --configuration netcoreapp3.1 --function-handler Blazure.Api::Blazure.Api.LambdaEntryPoint::FunctionHandlerAsync --function-runtime dotnetcore3.1 --function-name blazure-api --function-memory-size 128 --function-timeout 10
